dependencies:
  factories:
    Zend\Expressive\Router\RouterInterface: Articus\PathHandler\Router\Factory\FastRouteAnnotation

Articus\PathHandler\Middleware:
  metadata_cache:
    adapter:
      name: blackhole
  handlers:
    abstract_factories:
      - Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory
#  consumers:
#    factories:
#    invokables:
#  attributes:
#    factories:
#    invokables:
#  producers:
#    factories:
#    invokables:

Articus\PathHandler\Router\FastRouteAnnotation:
  metadata_cache:
    adapter:
      name: blackhole
  handlers:
    - App\Handler\CqactionsHtml
    - App\Handler\AppsSystemConfigComAdobeGraniteAuthSamlSamlAuthenticationHandlerConfig
    - App\Handler\AppsSystemConfigComShinesolutionsAemPasswordresetActivator
    - App\Handler\AppsSystemConfigComShinesolutionsHealthcheckHcImplActiveBundleHealthCheck
    - App\Handler\AppsSystemConfigOrgApacheFelixHttp
    - App\Handler\AppsSystemConfigOrgApacheHttpProxyconfiguratorConfig
    - App\Handler\AppsSystemConfigOrgApacheSlingJcrDavexImplServletsSlingDavExServlet
    - App\Handler\AppsSystemConfigOrgApacheSlingSecurityImplReferrerFilter
    - App\Handler\AppsSystemConfigOrgApacheSlingServletsGetDefaultGetServlet
    - App\Handler\BinQuerybuilderJson
    - App\Handler\CrxExplorerUiSetpasswordJsp
    - App\Handler\CrxPackmgrInstallstatusJsp
    - App\Handler\CrxPackmgrServiceJsp
    - App\Handler\CrxPackmgrServiceJsonPath
    - App\Handler\CrxPackmgrServiceScriptHtml
    - App\Handler\CrxPackmgrUpdateJsp
    - App\Handler\CrxServerCrxDefaultJcrRoot1Json
    - App\Handler\EtcPackagesGroupNameVersionZip
    - App\Handler\EtcPackagesGroupNameVersionZipJcrContentVltDefinitionFilterTidy2Json
    - App\Handler\EtcReplicationAgentsRunmode1Json
    - App\Handler\EtcReplicationAgentsRunmodeName
    - App\Handler\EtcReplicationTreeactivationHtml
    - App\Handler\EtcTruststore
    - App\Handler\EtcTruststoreTruststoreP12
    - App\Handler\LibsGraniteCoreContentLoginHtml
    - App\Handler\LibsGraniteSecurityPostAuthorizables
    - App\Handler\LibsGraniteSecurityPostTruststore
    - App\Handler\LibsGraniteSecurityTruststoreJson
    - App\Handler\SystemConsoleBundlesName
    - App\Handler\SystemConsoleConfigMgr
    - App\Handler\SystemConsoleConfigMgrComAdobeGraniteAuthSamlSamlAuthenticationHandler
    - App\Handler\SystemConsoleJmxComAdobeGraniteTypeRepositoryOpAction
    - App\Handler\SystemConsoleStatusProductinfoJson
    - App\Handler\SystemHealth
    - App\Handler\IntermediatePathAuthorizableIdKsHtml
    - App\Handler\IntermediatePathAuthorizableIdKsJson
    - App\Handler\IntermediatePathAuthorizableIdKeystoreStoreP12
    - App\Handler\Path
    - App\Handler\PathName
    - App\Handler\PathNameRwHtml

Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory:
  App\Handler\CqactionsHtml: []
  App\Handler\AppsSystemConfigComAdobeGraniteAuthSamlSamlAuthenticationHandlerConfig: []
  App\Handler\AppsSystemConfigComShinesolutionsAemPasswordresetActivator: []
  App\Handler\AppsSystemConfigComShinesolutionsHealthcheckHcImplActiveBundleHealthCheck: []
  App\Handler\AppsSystemConfigOrgApacheFelixHttp: []
  App\Handler\AppsSystemConfigOrgApacheHttpProxyconfiguratorConfig: []
  App\Handler\AppsSystemConfigOrgApacheSlingJcrDavexImplServletsSlingDavExServlet: []
  App\Handler\AppsSystemConfigOrgApacheSlingSecurityImplReferrerFilter: []
  App\Handler\AppsSystemConfigOrgApacheSlingServletsGetDefaultGetServlet: []
  App\Handler\BinQuerybuilderJson: []
  App\Handler\CrxExplorerUiSetpasswordJsp: []
  App\Handler\CrxPackmgrInstallstatusJsp: []
  App\Handler\CrxPackmgrServiceJsp: []
  App\Handler\CrxPackmgrServiceJsonPath: []
  App\Handler\CrxPackmgrServiceScriptHtml: []
  App\Handler\CrxPackmgrUpdateJsp: []
  App\Handler\CrxServerCrxDefaultJcrRoot1Json: []
  App\Handler\EtcPackagesGroupNameVersionZip: []
  App\Handler\EtcPackagesGroupNameVersionZipJcrContentVltDefinitionFilterTidy2Json: []
  App\Handler\EtcReplicationAgentsRunmode1Json: []
  App\Handler\EtcReplicationAgentsRunmodeName: []
  App\Handler\EtcReplicationTreeactivationHtml: []
  App\Handler\EtcTruststore: []
  App\Handler\EtcTruststoreTruststoreP12: []
  App\Handler\LibsGraniteCoreContentLoginHtml: []
  App\Handler\LibsGraniteSecurityPostAuthorizables: []
  App\Handler\LibsGraniteSecurityPostTruststore: []
  App\Handler\LibsGraniteSecurityTruststoreJson: []
  App\Handler\SystemConsoleBundlesName: []
  App\Handler\SystemConsoleConfigMgr: []
  App\Handler\SystemConsoleConfigMgrComAdobeGraniteAuthSamlSamlAuthenticationHandler: []
  App\Handler\SystemConsoleJmxComAdobeGraniteTypeRepositoryOpAction: []
  App\Handler\SystemConsoleStatusProductinfoJson: []
  App\Handler\SystemHealth: []
  App\Handler\IntermediatePathAuthorizableIdKsHtml: []
  App\Handler\IntermediatePathAuthorizableIdKsJson: []
  App\Handler\IntermediatePathAuthorizableIdKeystoreStoreP12: []
  App\Handler\Path: []
  App\Handler\PathName: []
  App\Handler\PathNameRwHtml: []
